/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ClimateWitness {
  export type EventGroupStruct = {
    creator: AddressLike;
    groupCID: string;
    createdAt: BigNumberish;
  };

  export type EventGroupStructOutput = [
    creator: string,
    groupCID: string,
    createdAt: bigint
  ] & { creator: string; groupCID: string; createdAt: bigint };

  export type WitnessStruct = {
    submitter: AddressLike;
    eventType: BigNumberish;
    evidenceCID: string;
    sensorHash: BytesLike;
    locationHash: BytesLike;
    timestamp: BigNumberish;
    status: BigNumberish;
    verifyCount: BigNumberish;
    rejectCount: BigNumberish;
    encryptedSeverity: BytesLike;
    encryptedRainfall: BytesLike;
    encryptedHasMediaKey: BytesLike;
  };

  export type WitnessStructOutput = [
    submitter: string,
    eventType: bigint,
    evidenceCID: string,
    sensorHash: string,
    locationHash: string,
    timestamp: bigint,
    status: bigint,
    verifyCount: bigint,
    rejectCount: bigint,
    encryptedSeverity: string,
    encryptedRainfall: string,
    encryptedHasMediaKey: string
  ] & {
    submitter: string;
    eventType: bigint;
    evidenceCID: string;
    sensorHash: string;
    locationHash: string;
    timestamp: bigint;
    status: bigint;
    verifyCount: bigint;
    rejectCount: bigint;
    encryptedSeverity: string;
    encryptedRainfall: string;
    encryptedHasMediaKey: string;
  };
}

export interface ClimateWitnessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attachWitnessToGroup"
      | "contestWitness"
      | "createEventGroup"
      | "getEncryptedVerifyThreshold"
      | "getGroup"
      | "getVerifyThreshold"
      | "getWitness"
      | "governance"
      | "hasVerified"
      | "nextGroupId"
      | "nextWitnessId"
      | "protocolId"
      | "setVerifier"
      | "setVerifyThreshold"
      | "submitWitness"
      | "transferGovernance"
      | "verifiers"
      | "verifyWitness"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EventGroupCreated"
      | "GovernanceTransferred"
      | "WitnessAttached"
      | "WitnessSubmitted"
      | "WitnessVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attachWitnessToGroup",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contestWitness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEventGroup",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedVerifyThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGroup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifyThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWitness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVerified",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGroupId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextWitnessId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifyThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWitness",
    values: [
      BigNumberish,
      BytesLike,
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyWitness",
    values: [BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "attachWitnessToGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contestWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEventGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedVerifyThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGroup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerifyThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWitness", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextGroupId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextWitnessId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifyThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyWitness",
    data: BytesLike
  ): Result;
}

export namespace EventGroupCreatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    creator: AddressLike,
    groupCID: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    creator: string,
    groupCID: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    creator: string;
    groupCID: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceTransferredEvent {
  export type InputTuple = [previousGov: AddressLike, newGov: AddressLike];
  export type OutputTuple = [previousGov: string, newGov: string];
  export interface OutputObject {
    previousGov: string;
    newGov: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessAttachedEvent {
  export type InputTuple = [groupId: BigNumberish, witnessId: BigNumberish];
  export type OutputTuple = [groupId: bigint, witnessId: bigint];
  export interface OutputObject {
    groupId: bigint;
    witnessId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessSubmittedEvent {
  export type InputTuple = [
    witnessId: BigNumberish,
    submitter: AddressLike,
    eventType: BigNumberish,
    evidenceCID: string,
    locationHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    witnessId: bigint,
    submitter: string,
    eventType: bigint,
    evidenceCID: string,
    locationHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    witnessId: bigint;
    submitter: string;
    eventType: bigint;
    evidenceCID: string;
    locationHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessVerifiedEvent {
  export type InputTuple = [
    witnessId: BigNumberish,
    verifier: AddressLike,
    approve: boolean,
    verifyCID: string,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    witnessId: bigint,
    verifier: string,
    approve: boolean,
    verifyCID: string,
    updatedAt: bigint
  ];
  export interface OutputObject {
    witnessId: bigint;
    verifier: string;
    approve: boolean;
    verifyCID: string;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClimateWitness extends BaseContract {
  connect(runner?: ContractRunner | null): ClimateWitness;
  waitForDeployment(): Promise<this>;

  interface: ClimateWitnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attachWitnessToGroup: TypedContractMethod<
    [groupId: BigNumberish, witnessId: BigNumberish],
    [void],
    "nonpayable"
  >;

  contestWitness: TypedContractMethod<
    [witnessId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEventGroup: TypedContractMethod<
    [groupCID: string],
    [bigint],
    "nonpayable"
  >;

  getEncryptedVerifyThreshold: TypedContractMethod<[], [string], "view">;

  getGroup: TypedContractMethod<
    [groupId: BigNumberish],
    [
      [ClimateWitness.EventGroupStructOutput, bigint[]] & {
        group: ClimateWitness.EventGroupStructOutput;
        witnessIds: bigint[];
      }
    ],
    "view"
  >;

  getVerifyThreshold: TypedContractMethod<[], [bigint], "view">;

  getWitness: TypedContractMethod<
    [witnessId: BigNumberish],
    [ClimateWitness.WitnessStructOutput],
    "view"
  >;

  governance: TypedContractMethod<[], [string], "view">;

  hasVerified: TypedContractMethod<
    [witnessId: BigNumberish, verifier: AddressLike],
    [boolean],
    "view"
  >;

  nextGroupId: TypedContractMethod<[], [bigint], "view">;

  nextWitnessId: TypedContractMethod<[], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setVerifier: TypedContractMethod<
    [account: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setVerifyThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitWitness: TypedContractMethod<
    [
      eventType: BigNumberish,
      locationHash: BytesLike,
      evidenceCID: string,
      sensorHash: BytesLike,
      encryptedSeverityExt: BytesLike,
      severityProof: BytesLike,
      encryptedRainfallExt: BytesLike,
      rainfallProof: BytesLike,
      encryptedHasMediaKeyExt: BytesLike,
      mediaProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  transferGovernance: TypedContractMethod<
    [newGov: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifyWitness: TypedContractMethod<
    [witnessId: BigNumberish, approve: boolean, verifyCID: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attachWitnessToGroup"
  ): TypedContractMethod<
    [groupId: BigNumberish, witnessId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contestWitness"
  ): TypedContractMethod<[witnessId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEventGroup"
  ): TypedContractMethod<[groupCID: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedVerifyThreshold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGroup"
  ): TypedContractMethod<
    [groupId: BigNumberish],
    [
      [ClimateWitness.EventGroupStructOutput, bigint[]] & {
        group: ClimateWitness.EventGroupStructOutput;
        witnessIds: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifyThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWitness"
  ): TypedContractMethod<
    [witnessId: BigNumberish],
    [ClimateWitness.WitnessStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasVerified"
  ): TypedContractMethod<
    [witnessId: BigNumberish, verifier: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextGroupId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextWitnessId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<
    [account: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifyThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitWitness"
  ): TypedContractMethod<
    [
      eventType: BigNumberish,
      locationHash: BytesLike,
      evidenceCID: string,
      sensorHash: BytesLike,
      encryptedSeverityExt: BytesLike,
      severityProof: BytesLike,
      encryptedRainfallExt: BytesLike,
      rainfallProof: BytesLike,
      encryptedHasMediaKeyExt: BytesLike,
      mediaProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferGovernance"
  ): TypedContractMethod<[newGov: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyWitness"
  ): TypedContractMethod<
    [witnessId: BigNumberish, approve: boolean, verifyCID: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EventGroupCreated"
  ): TypedContractEvent<
    EventGroupCreatedEvent.InputTuple,
    EventGroupCreatedEvent.OutputTuple,
    EventGroupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceTransferred"
  ): TypedContractEvent<
    GovernanceTransferredEvent.InputTuple,
    GovernanceTransferredEvent.OutputTuple,
    GovernanceTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WitnessAttached"
  ): TypedContractEvent<
    WitnessAttachedEvent.InputTuple,
    WitnessAttachedEvent.OutputTuple,
    WitnessAttachedEvent.OutputObject
  >;
  getEvent(
    key: "WitnessSubmitted"
  ): TypedContractEvent<
    WitnessSubmittedEvent.InputTuple,
    WitnessSubmittedEvent.OutputTuple,
    WitnessSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WitnessVerified"
  ): TypedContractEvent<
    WitnessVerifiedEvent.InputTuple,
    WitnessVerifiedEvent.OutputTuple,
    WitnessVerifiedEvent.OutputObject
  >;

  filters: {
    "EventGroupCreated(uint256,address,string,uint256)": TypedContractEvent<
      EventGroupCreatedEvent.InputTuple,
      EventGroupCreatedEvent.OutputTuple,
      EventGroupCreatedEvent.OutputObject
    >;
    EventGroupCreated: TypedContractEvent<
      EventGroupCreatedEvent.InputTuple,
      EventGroupCreatedEvent.OutputTuple,
      EventGroupCreatedEvent.OutputObject
    >;

    "GovernanceTransferred(address,address)": TypedContractEvent<
      GovernanceTransferredEvent.InputTuple,
      GovernanceTransferredEvent.OutputTuple,
      GovernanceTransferredEvent.OutputObject
    >;
    GovernanceTransferred: TypedContractEvent<
      GovernanceTransferredEvent.InputTuple,
      GovernanceTransferredEvent.OutputTuple,
      GovernanceTransferredEvent.OutputObject
    >;

    "WitnessAttached(uint256,uint256)": TypedContractEvent<
      WitnessAttachedEvent.InputTuple,
      WitnessAttachedEvent.OutputTuple,
      WitnessAttachedEvent.OutputObject
    >;
    WitnessAttached: TypedContractEvent<
      WitnessAttachedEvent.InputTuple,
      WitnessAttachedEvent.OutputTuple,
      WitnessAttachedEvent.OutputObject
    >;

    "WitnessSubmitted(uint256,address,uint8,string,bytes32,uint256)": TypedContractEvent<
      WitnessSubmittedEvent.InputTuple,
      WitnessSubmittedEvent.OutputTuple,
      WitnessSubmittedEvent.OutputObject
    >;
    WitnessSubmitted: TypedContractEvent<
      WitnessSubmittedEvent.InputTuple,
      WitnessSubmittedEvent.OutputTuple,
      WitnessSubmittedEvent.OutputObject
    >;

    "WitnessVerified(uint256,address,bool,string,uint256)": TypedContractEvent<
      WitnessVerifiedEvent.InputTuple,
      WitnessVerifiedEvent.OutputTuple,
      WitnessVerifiedEvent.OutputObject
    >;
    WitnessVerified: TypedContractEvent<
      WitnessVerifiedEvent.InputTuple,
      WitnessVerifiedEvent.OutputTuple,
      WitnessVerifiedEvent.OutputObject
    >;
  };
}
