/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TempestSentinel {
  export type PulseRecordStruct = {
    submitter: AddressLike;
    eventType: BigNumberish;
    evidenceCID: string;
    sensorHash: BytesLike;
    locationHash: BytesLike;
    timestamp: BigNumberish;
    status: BigNumberish;
    approveCount: BigNumberish;
    rejectCount: BigNumberish;
    encryptedIntensity: BytesLike;
    encryptedPrecipitation: BytesLike;
    encryptedHasMediaKey: BytesLike;
  };

  export type PulseRecordStructOutput = [
    submitter: string,
    eventType: bigint,
    evidenceCID: string,
    sensorHash: string,
    locationHash: string,
    timestamp: bigint,
    status: bigint,
    approveCount: bigint,
    rejectCount: bigint,
    encryptedIntensity: string,
    encryptedPrecipitation: string,
    encryptedHasMediaKey: string
  ] & {
    submitter: string;
    eventType: bigint;
    evidenceCID: string;
    sensorHash: string;
    locationHash: string;
    timestamp: bigint;
    status: bigint;
    approveCount: bigint;
    rejectCount: bigint;
    encryptedIntensity: string;
    encryptedPrecipitation: string;
    encryptedHasMediaKey: string;
  };

  export type StormChannelStruct = {
    creator: AddressLike;
    groupCID: string;
    createdAt: BigNumberish;
  };

  export type StormChannelStructOutput = [
    creator: string,
    groupCID: string,
    createdAt: bigint
  ] & { creator: string; groupCID: string; createdAt: bigint };
}

export interface TempestSentinelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditors"
      | "confidentialProtocolId"
      | "configureAuditThreshold"
      | "configureAuditor"
      | "coordination"
      | "createStormChannel"
      | "escalatePulse"
      | "getAuditThreshold"
      | "getEncryptedAuditThreshold"
      | "getPulse"
      | "getStormChannel"
      | "hasReviewed"
      | "linkPulseToChannel"
      | "logPulse"
      | "nextChannelId"
      | "nextRecordId"
      | "reviewPulse"
      | "transferCoordination"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoordinationTransferred"
      | "PulseLinked"
      | "PulseLogged"
      | "PulseReviewed"
      | "StormChannelCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auditors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configureAuditThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configureAuditor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "coordination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createStormChannel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "escalatePulse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedAuditThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPulse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStormChannel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "linkPulseToChannel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logPulse",
    values: [
      BigNumberish,
      BytesLike,
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nextChannelId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextRecordId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewPulse",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferCoordination",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "auditors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureAuditThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coordination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStormChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escalatePulse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedAuditThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPulse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStormChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkPulseToChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logPulse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextChannelId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRecordId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewPulse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCoordination",
    data: BytesLike
  ): Result;
}

export namespace CoordinationTransferredEvent {
  export type InputTuple = [
    previousCoordination: AddressLike,
    newCoordination: AddressLike
  ];
  export type OutputTuple = [
    previousCoordination: string,
    newCoordination: string
  ];
  export interface OutputObject {
    previousCoordination: string;
    newCoordination: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulseLinkedEvent {
  export type InputTuple = [channelId: BigNumberish, recordId: BigNumberish];
  export type OutputTuple = [channelId: bigint, recordId: bigint];
  export interface OutputObject {
    channelId: bigint;
    recordId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulseLoggedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    submitter: AddressLike,
    eventType: BigNumberish,
    evidenceCID: string,
    locationHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: bigint,
    submitter: string,
    eventType: bigint,
    evidenceCID: string,
    locationHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: bigint;
    submitter: string;
    eventType: bigint;
    evidenceCID: string;
    locationHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulseReviewedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    auditor: AddressLike,
    endorse: boolean,
    reviewCID: string,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    recordId: bigint,
    auditor: string,
    endorse: boolean,
    reviewCID: string,
    updatedAt: bigint
  ];
  export interface OutputObject {
    recordId: bigint;
    auditor: string;
    endorse: boolean;
    reviewCID: string;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StormChannelCreatedEvent {
  export type InputTuple = [
    channelId: BigNumberish,
    creator: AddressLike,
    groupCID: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    channelId: bigint,
    creator: string,
    groupCID: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    channelId: bigint;
    creator: string;
    groupCID: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TempestSentinel extends BaseContract {
  connect(runner?: ContractRunner | null): TempestSentinel;
  waitForDeployment(): Promise<this>;

  interface: TempestSentinelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  configureAuditThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  configureAuditor: TypedContractMethod<
    [account: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  coordination: TypedContractMethod<[], [string], "view">;

  createStormChannel: TypedContractMethod<
    [groupCID: string],
    [bigint],
    "nonpayable"
  >;

  escalatePulse: TypedContractMethod<
    [recordId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAuditThreshold: TypedContractMethod<[], [bigint], "view">;

  getEncryptedAuditThreshold: TypedContractMethod<[], [string], "view">;

  getPulse: TypedContractMethod<
    [recordId: BigNumberish],
    [TempestSentinel.PulseRecordStructOutput],
    "view"
  >;

  getStormChannel: TypedContractMethod<
    [channelId: BigNumberish],
    [
      [TempestSentinel.StormChannelStructOutput, bigint[]] & {
        channel: TempestSentinel.StormChannelStructOutput;
        recordIds: bigint[];
      }
    ],
    "view"
  >;

  hasReviewed: TypedContractMethod<
    [recordId: BigNumberish, auditor: AddressLike],
    [boolean],
    "view"
  >;

  linkPulseToChannel: TypedContractMethod<
    [channelId: BigNumberish, recordId: BigNumberish],
    [void],
    "nonpayable"
  >;

  logPulse: TypedContractMethod<
    [
      eventType: BigNumberish,
      locationHash: BytesLike,
      evidenceCID: string,
      sensorHash: BytesLike,
      encryptedIntensityExt: BytesLike,
      intensityProof: BytesLike,
      encryptedPrecipitationExt: BytesLike,
      precipitationProof: BytesLike,
      encryptedHasMediaKeyExt: BytesLike,
      mediaProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  nextChannelId: TypedContractMethod<[], [bigint], "view">;

  nextRecordId: TypedContractMethod<[], [bigint], "view">;

  reviewPulse: TypedContractMethod<
    [recordId: BigNumberish, endorse: boolean, reviewCID: string],
    [void],
    "nonpayable"
  >;

  transferCoordination: TypedContractMethod<
    [newCoordination: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "configureAuditThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configureAuditor"
  ): TypedContractMethod<
    [account: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "coordination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createStormChannel"
  ): TypedContractMethod<[groupCID: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "escalatePulse"
  ): TypedContractMethod<[recordId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuditThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedAuditThreshold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPulse"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [TempestSentinel.PulseRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStormChannel"
  ): TypedContractMethod<
    [channelId: BigNumberish],
    [
      [TempestSentinel.StormChannelStructOutput, bigint[]] & {
        channel: TempestSentinel.StormChannelStructOutput;
        recordIds: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [recordId: BigNumberish, auditor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "linkPulseToChannel"
  ): TypedContractMethod<
    [channelId: BigNumberish, recordId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logPulse"
  ): TypedContractMethod<
    [
      eventType: BigNumberish,
      locationHash: BytesLike,
      evidenceCID: string,
      sensorHash: BytesLike,
      encryptedIntensityExt: BytesLike,
      intensityProof: BytesLike,
      encryptedPrecipitationExt: BytesLike,
      precipitationProof: BytesLike,
      encryptedHasMediaKeyExt: BytesLike,
      mediaProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextChannelId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRecordId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reviewPulse"
  ): TypedContractMethod<
    [recordId: BigNumberish, endorse: boolean, reviewCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferCoordination"
  ): TypedContractMethod<[newCoordination: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CoordinationTransferred"
  ): TypedContractEvent<
    CoordinationTransferredEvent.InputTuple,
    CoordinationTransferredEvent.OutputTuple,
    CoordinationTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PulseLinked"
  ): TypedContractEvent<
    PulseLinkedEvent.InputTuple,
    PulseLinkedEvent.OutputTuple,
    PulseLinkedEvent.OutputObject
  >;
  getEvent(
    key: "PulseLogged"
  ): TypedContractEvent<
    PulseLoggedEvent.InputTuple,
    PulseLoggedEvent.OutputTuple,
    PulseLoggedEvent.OutputObject
  >;
  getEvent(
    key: "PulseReviewed"
  ): TypedContractEvent<
    PulseReviewedEvent.InputTuple,
    PulseReviewedEvent.OutputTuple,
    PulseReviewedEvent.OutputObject
  >;
  getEvent(
    key: "StormChannelCreated"
  ): TypedContractEvent<
    StormChannelCreatedEvent.InputTuple,
    StormChannelCreatedEvent.OutputTuple,
    StormChannelCreatedEvent.OutputObject
  >;

  filters: {
    "CoordinationTransferred(address,address)": TypedContractEvent<
      CoordinationTransferredEvent.InputTuple,
      CoordinationTransferredEvent.OutputTuple,
      CoordinationTransferredEvent.OutputObject
    >;
    CoordinationTransferred: TypedContractEvent<
      CoordinationTransferredEvent.InputTuple,
      CoordinationTransferredEvent.OutputTuple,
      CoordinationTransferredEvent.OutputObject
    >;

    "PulseLinked(uint256,uint256)": TypedContractEvent<
      PulseLinkedEvent.InputTuple,
      PulseLinkedEvent.OutputTuple,
      PulseLinkedEvent.OutputObject
    >;
    PulseLinked: TypedContractEvent<
      PulseLinkedEvent.InputTuple,
      PulseLinkedEvent.OutputTuple,
      PulseLinkedEvent.OutputObject
    >;

    "PulseLogged(uint256,address,uint8,string,bytes32,uint256)": TypedContractEvent<
      PulseLoggedEvent.InputTuple,
      PulseLoggedEvent.OutputTuple,
      PulseLoggedEvent.OutputObject
    >;
    PulseLogged: TypedContractEvent<
      PulseLoggedEvent.InputTuple,
      PulseLoggedEvent.OutputTuple,
      PulseLoggedEvent.OutputObject
    >;

    "PulseReviewed(uint256,address,bool,string,uint256)": TypedContractEvent<
      PulseReviewedEvent.InputTuple,
      PulseReviewedEvent.OutputTuple,
      PulseReviewedEvent.OutputObject
    >;
    PulseReviewed: TypedContractEvent<
      PulseReviewedEvent.InputTuple,
      PulseReviewedEvent.OutputTuple,
      PulseReviewedEvent.OutputObject
    >;

    "StormChannelCreated(uint256,address,string,uint256)": TypedContractEvent<
      StormChannelCreatedEvent.InputTuple,
      StormChannelCreatedEvent.OutputTuple,
      StormChannelCreatedEvent.OutputObject
    >;
    StormChannelCreated: TypedContractEvent<
      StormChannelCreatedEvent.InputTuple,
      StormChannelCreatedEvent.OutputTuple,
      StormChannelCreatedEvent.OutputObject
    >;
  };
}
